#!/bin/bash
set -e

if [[ $# = 1 ]]; then
  sub_uri="$1"
  esc_sub_uri="${sub_uri//&/\\&}"
else
  echo >&2 "Only one argument required"
  exit 1
fi

tmp_files=
ecode=1

exit_notice() {
  if [[ $ecode = 0 ]]; then
    notice "Successfully added cache '$sub_uri'"
  else
    notice "Failed to add cache '$sub_uri'"
    exit $ecode
  fi
}

trap 'trap - EXIT;if [[ -n "${tmp_files[@]}" ]]; then rm -rf "${tmp_files[@]}"; fi; exit_notice' EXIT

root_conf="/etc/nix/nix.conf"
user_conf="${XDG_CONFIG_HOME:-$HOME/.config}/nix/nix.conf"

notice() {
  cat >&2 <<EOF

------------------------------------------------------------------------------
$(echo "$1" | fmt -w79)
------------------------------------------------------------------------------
EOF
}

try_sudo() { 
  "$@" 2>/dev/null || sudo "$@"
}

is_added() {
  grep -q "^substituters =.*\( \|\b\)$sub_uri\( \|$\)" "$1"
}

is_trusted_user() {
  if grep -q "^trusted-users =.*\b$USER\b" "$root_conf"; then
    return 0
  fi
  return 1
}

edit_conf() {
  local conf_file
  local tmp_file
  conf_file="$1"
  tmp_file="${TEMP:-/tmp}/nix-conf.$(head -c5 /dev/random | basenc --base32)"
  tmp_files+=("$tmp_file")

  cp "$conf_file" "$tmp_file"

  if grep -q "^substituters =" "$tmp_file"; then
    sed -i'' "s|^substituters =.*$|\0 $esc_sub_uri|" "$tmp_file"
  else
    echo "substituters = https://cache.nixos.org $sub_uri" >> "$tmp_file"
  fi

  if diff -u "$conf_file" "$tmp_file"; then
    echo >&2 "No changes to apply"
    return 0
  fi

  notice "Apply changes to $conf_file?"
  echo -n >&2 "Type 'yes' and press enter to continue: "
  read -r answer

  if [[ $answer = yes ]]; then
    if try_sudo cp "$tmp_file" "$conf_file"; then
      notice "Successfully updated config: $conf_file"
      if [[ $conf_file = "$root_conf" ]]; then
        notice "Note: Restart of nix-daemon is required for changes to take effect"
      fi
      return 0
    else
      notice "Failed to update config: $conf_file"
      return 1
    fi
  else
    notice "No changes applied to: $conf_file"
    return 1
  fi
}


add_sub() {
  if is_added "$root_conf" && is_added "$user_conf"; then
    notice "Substituter URI '$sub_uri' is already in root ($root_conf) and user config ($user_conf)"
    return 0
  fi

  if is_trusted_user && is_added "$user_conf"; then
    notice "Substituter URI '$sub_uri' is already in user config ($user_conf) and your user ($USER) is trusted by root config ($root_conf)"
    return 0
  fi

  if  is_trusted_user; then
    notice "Your user ($USER) is trusted by root config ($root_conf)"
  elif is_added "$root_conf"; then :
    notice "Substituter URI '$sub_uri' is already in root config ($root_conf)"
  else
    notice "Need to edit root config $root_conf

NOTE: This may require SUDO
"
    edit_conf "$root_conf" || return 1
  fi

  if is_added "$user_conf"; then :
  else
    notice "Need to edit user config $user_conf"
    edit_conf "$user_conf" || return 1
  fi
}

add_sub
ecode=0
