#!/bin/bash
set -ex

SECRET_KEY="${SECRET_KEY:-$1}"
CACHE_URI="s3://${CACHE_NAME:-nix-cache-testing}?endpoint=https://storage.googleapis.com&profile=gcp"

export AWS_EC2_METADATA_DISABLED=true

mapfile -t OUT_PATH

echo "${OUT_PATH[@]}"

if [[ -f $SECRET_KEY ]]; then
  echo "Signing paths with $SECRET_KEY..."
  nix store sign -k "$SECRET_KEY" "${OUT_PATH[@]}"
fi

echo "Copying paths to $CACHE_URI..."
nix copy --to "$CACHE_URI" "${OUT_PATH[@]}"
